name: check and build pull requests

on:
  pull_request: []

jobs:
  build-website:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@master

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install GitHub Pages, Bundler, and kramdown gems
        run: |
          gem install bundler:2.4.22 yaml-lint

      - name: Set up caching for Bundler
        uses: actions/cache@v2
        with:
          path: .vendor/bundle
          key: gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            gems-

      - name: Install & Update Ruby Gems
        run: |
          bundle config path .vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle update

      - name: Lint _config.yml with yaml-lint
        run: |
          yaml-lint  _config.yml

      - name: Lint pages and blog posts
        run: |
          yaml-lint -q -n $(find _posts -regex ".*.md\|.*html") &&\
          yaml-lint -q -n $(find pages -regex ".*.md\|.*html")

      - name: Get GeoJSON for instructor map
        run: |
           curl --remote-name-all https://feeds.carpentries.org/all_instructors_by_airport.geojson &&\
           cp all_instructors_by_airport.geojson files/.

      - name: Create PDF file of some pages
        uses: docker://pandoc/latex:latest
        with:
          args: >
            --output files/pdf/online-workshop-recommendations.pdf
            --pdf-engine=xelatex
            -V geometry:margin=1in
            pages/online-workshop-recommendations.md

      - name: Build site
        run: make site
